projects:
  -
    name: Linee Guida ex art. 71 del CAD
    description: "Configurazione generale per le Linee Guida ex art 71 del CAD; Servizio Accreditamento"
    website: https://github.com/test-lg/
    documents:
      - index.rst
    logo: assets/images/AgID_logotype-h_white_it_mid.png
    tags:
      - CAD
      - eIDAS
      - GDPR
